In [21]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np
import harmonizome.utility_functions as uf
import utility_functions2 as uf
import string

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [48]:
df = pd.DataFrame(np.concatenate((
    np.reshape(np.array(list(map(chr, range(97, 107)))), (10,1)), 
    np.random.randint(-1, high=2, size=(10, 9))), axis=1), 
    columns=['gene'] + list('ABCDEFGHI'))
df.set_index('gene', inplace=True)
df

A   B   C   D   E   F   G   H   I
gene                                    
a      0   0   0   0   1  -1   1   1  -1
b      1  -1  -1  -1  -1  -1  -1   0   1
c      1   0  -1   1   0  -1   1   0  -1
d      1  -1  -1   0  -1  -1   1   1  -1
e     -1   0   1   1   1   1  -1   1   1
f      0   1   1   0   0   0   0  -1   0
g     -1   0   1   0   0  -1   0  -1   1
h     -1   1   0  -1   0   0  -1  -1  -1
i      1   1   0  -1   1  -1   1  -1   1
j      1   1  -1  -1  -1   1  -1  -1   0

In [50]:
arr = df.reset_index(drop=True).to_numpy(dtype=np.int_)
arr

array([[ 0,  0,  0,  0,  1, -1,  1,  1, -1],
       [ 1, -1, -1, -1, -1, -1, -1,  0,  1],
       [ 1,  0, -1,  1,  0, -1,  1,  0, -1],
       [ 1, -1, -1,  0, -1, -1,  1,  1, -1],
       [-1,  0,  1,  1,  1,  1, -1,  1,  1],
       [ 0,  1,  1,  0,  0,  0,  0, -1,  0],
       [-1,  0,  1,  0,  0, -1,  0, -1,  1],
       [-1,  1,  0, -1,  0,  0, -1, -1, -1],
       [ 1,  1,  0, -1,  1, -1,  1, -1,  1],
       [ 1,  1, -1, -1, -1,  1, -1, -1,  0]])

In [54]:
num = (arr == 1).sum(axis=0)
num

array([5, 4, 3, 2, 3, 2, 4, 3, 4])

In [80]:
print(np.logical_and(num > 2, num <= 5))
reduced_arr = arr[:, np.logical_and(num > 2, num <= 5)]
attributes = df.columns[np.logical_and(num > 2, num <= 5)]
print(reduced_arr)
print(attributes)

[ True  True  True False  True False  True  True  True]
[[ 0  0  0  1  1  1 -1]
 [ 1 -1 -1 -1 -1  0  1]
 [ 1  0 -1  0  1  0 -1]
 [ 1 -1 -1 -1  1  1 -1]
 [-1  0  1  1 -1  1  1]
 [ 0  1  1  0  0 -1  0]
 [-1  0  1  0  0 -1  1]
 [-1  1  0  0 -1 -1 -1]
 [ 1  1  0  1  1 -1  1]
 [ 1  1 -1 -1 -1 -1  0]]
Index(['A', 'B', 'C', 'E', 'G', 'H', 'I'], dtype='object')


In [85]:
w, h = reduced_arr.shape
details = [i for i in range(10)]
for i in range(h):
    print(attributes[i], details[i] if details else 'NA', *df.index[reduced_arr[:, i] == 1], sep='\t', end='\n')

A	0	b	c	d	i	j
B	1	f	h	i	j
C	2	e	f	g
E	3	a	e	i
G	4	a	c	d	i
H	5	a	d	e
I	6	b	e	g	i
