In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np
import utility_functions2 as uf
import string
import itertools
import timeit

In [2]:
n = 200
name_gen = map(''.join, itertools.islice(itertools.product('ABCDE',repeat=10), n))
names = list(name_gen)

In [3]:
data = np.triu(np.random.random((n, n)))
data = (data + data.T) / 2
data

array([[0.66851507, 0.06608999, 0.09715327, ..., 0.49266884, 0.45831353,
        0.4848307 ],
       [0.06608999, 0.20532785, 0.16705056, ..., 0.39359968, 0.18832269,
        0.36840867],
       [0.09715327, 0.16705056, 0.47694386, ..., 0.40730195, 0.36444305,
        0.41675811],
       ...,
       [0.49266884, 0.39359968, 0.40730195, ..., 0.48622358, 0.04726204,
        0.19874665],
       [0.45831353, 0.18832269, 0.36444305, ..., 0.04726204, 0.29904151,
        0.24822672],
       [0.4848307 , 0.36840867, 0.41675811, ..., 0.19874665, 0.24822672,
        0.94968819]])

In [4]:
df = pd.DataFrame(data, index=names, columns=names)
df.astype(np.float16)
df

AAAAAAAAAA  AAAAAAAAAB  AAAAAAAAAC  AAAAAAAAAD  AAAAAAAAAE  \
AAAAAAAAAA    0.668515    0.066090    0.097153    0.146187    0.398358   
AAAAAAAAAB    0.066090    0.205328    0.167051    0.464044    0.385779   
AAAAAAAAAC    0.097153    0.167051    0.476944    0.274754    0.439581   
AAAAAAAAAD    0.146187    0.464044    0.274754    0.173321    0.396151   
AAAAAAAAAE    0.398358    0.385779    0.439581    0.396151    0.298464   
...                ...         ...         ...         ...         ...   
AAAAAABCEA    0.361308    0.162079    0.389616    0.080356    0.209480   
AAAAAABCEB    0.219307    0.083941    0.323193    0.147434    0.139431   
AAAAAABCEC    0.492669    0.393600    0.407302    0.356779    0.181473   
AAAAAABCED    0.458314    0.188323    0.364443    0.060638    0.043875   
AAAAAABCEE    0.484831    0.368409    0.416758    0.302092    0.178185   

            AAAAAAAABA  AAAAAAAABB  AAAAAAAABC  AAAAAAAABD  AAAAAAAABE  ...  \
AAAAAAAAAA    0.449910    0.264191    0.479308    0.053315    0.387427  ...   
AAAAAAAAAB    0.438277    0.069439    0.375565    0.378569    0.438337  ...   
AAAAAAAAAC    0.333682    0.173665    0.063945    0.191809    0.343606  ...   
AAAAAAAAAD    0.008619    0.419537    0.329867    0.424842    0.499557  ...   
AAAAAAAAAE    0.387998    0.187783    0.354363    0.227154    0.140942  ...   
...                ...         ...         ...         ...         ...  ...   
AAAAAABCEA    0.242038    0.410610    0.423747    0.473025    0.304192  ...   
AAAAAABCEB    0.134821    0.240941    0.416288    0.224132    0.302008  ...   
AAAAAABCEC    0.017627    0.260558    0.343420    0.365805    0.204374  ...   
AAAAAABCED    0.184969    0.012359    0.280964    0.204152    0.417992  ...   
AAAAAABCEE    0.041602    0.090233    0.052163    0.307910    0.455366  ...   

            AAAAAABCDA  AAAAAABCDB  AAAAAABCDC  AAAAAABCDD  AAAAAABCDE  \
AAAAAAAAAA    0.483645    0.354641    0.018448    0.114630    0.219803   
AAAAAAAAAB    0.254414    0.232867    0.100058    0.207798    0.271247   
AAAAAAAAAC    0.322316    0.237799    0.179322    0.484524    0.469119   
AAAAAAAAAD    0.416966    0.244610    0.343707    0.306811    0.431860   
AAAAAAAAAE    0.011864    0.464445    0.477123    0.441524    0.053628   
...                ...         ...         ...         ...         ...   
AAAAAABCEA    0.163989    0.433463    0.274460    0.290403    0.407965   
AAAAAABCEB    0.450739    0.170000    0.255826    0.154141    0.324264   
AAAAAABCEC    0.298913    0.333648    0.379664    0.303181    0.308444   
AAAAAABCED    0.000516    0.491354    0.331580    0.041566    0.474403   
AAAAAABCEE    0.018876    0.468869    0.451960    0.150229    0.403463   

            AAAAAABCEA  AAAAAABCEB  AAAAAABCEC  AAAAAABCED  AAAAAABCEE  
AAAAAAAAAA    0.361308    0.219307    0.492669    0.458314    0.484831  
AAAAAAAAAB    0.162079    0.083941    0.393600    0.188323    0.368409  
AAAAAAAAAC    0.389616    0.323193    0.407302    0.364443    0.416758  
AAAAAAAAAD    0.080356    0.147434    0.356779    0.060638    0.302092  
AAAAAAAAAE    0.209480    0.139431    0.181473    0.043875    0.178185  
...                ...         ...         ...         ...         ...  
AAAAAABCEA    0.393643    0.331547    0.041608    0.157148    0.421128  
AAAAAABCEB    0.331547    0.268152    0.402614    0.270252    0.237515  
AAAAAABCEC    0.041608    0.402614    0.486224    0.047262    0.198747  
AAAAAABCED    0.157148    0.270252    0.047262    0.299042    0.248227  
AAAAAABCEE    0.421128    0.237515    0.198747    0.248227    0.949688  

[200 rows x 200 columns]

In [5]:
# %time df.to_csv('Output/similarity_to_csv.csv.gz', compression='gzip')
# %time np.savetxt('Output/similarity_savetext.txt', data.astype(np.float32), delimiter='\t')
# %time np.savez_compressed('Output/similarity_savez_compressed.npz', data.astype(np.float32), delimiter='\t')
# %time np.savez_compressed('Output/similarity_triu_savez_compressed.npz', data=np.triu(data.astype(np.float32)))

In [37]:
%time uf.saveData(df, 'Output/', 'similarity_triu_savez_compressed', compression='npz', axes=('gene', 'gene'), symmetric=True, dtype=np.float32)

CPU times: user 359 ms, sys: 0 ns, total: 359 ms
Wall time: 365 ms


In [44]:
%%time
with np.load('Output/similarity_triu_savez_compressed_2020_06.npz') as data_load:
    print(data_load.files)
    data = data_load[data_load.files[0]]
    data1 = data + data.T - np.diag(data.diagonal())
    print(data1)

['gene_gene_symmetric']
[[0.4672927  0.4082032  0.21324289 ... 0.19984746 0.35704136 0.30937678]
 [0.4082032  0.90034044 0.19457564 ... 0.11875503 0.06574276 0.4180302 ]
 [0.21324289 0.19457564 0.11525619 ... 0.10191019 0.10809419 0.36791253]
 ...
 [0.19984746 0.11875503 0.10191019 ... 0.9681779  0.20590833 0.42822033]
 [0.35704136 0.06574276 0.10809419 ... 0.20590833 0.60930616 0.04143846]
 [0.30937678 0.4180302  0.36791253 ... 0.42822033 0.04143846 0.57826126]]
CPU times: user 78.1 ms, sys: 15.6 ms, total: 93.8 ms
Wall time: 84.3 ms


In [39]:
%time uf.saveData(df, 'Output/', 'similarity_savez_compressed', compression='npz', axes=('gene', 'gene'), dtype=np.float32)

CPU times: user 641 ms, sys: 0 ns, total: 641 ms
Wall time: 654 ms


In [45]:
%%time
with np.load('Output/similarity_savez_compressed_2020_06.npz') as data_load:
    print(data_load.files)
    data2 = data_load[data_load.files[0]]
    print(data2)

['gene_gene']
[[0.4672927  0.4082032  0.21324289 ... 0.19984746 0.35704136 0.30937678]
 [0.4082032  0.90034044 0.19457564 ... 0.11875503 0.06574276 0.4180302 ]
 [0.21324289 0.19457564 0.11525619 ... 0.10191019 0.10809419 0.36791253]
 ...
 [0.19984746 0.11875503 0.10191019 ... 0.9681779  0.20590833 0.42822033]
 [0.35704136 0.06574276 0.10809419 ... 0.20590833 0.60930616 0.04143846]
 [0.30937678 0.4180302  0.36791253 ... 0.42822033 0.04143846 0.57826126]]
CPU times: user 78.1 ms, sys: 15.6 ms, total: 93.8 ms
Wall time: 88.4 ms


In [46]:
assert(np.all(np.equal(data1, data2)))

In [47]:
%time uf.saveData(df, 'Output/', 'similarity_to_csv', compression='gzip')

CPU times: user 16.8 s, sys: 578 ms, total: 17.3 s
Wall time: 17.4 s
